server:
  port: 8001

spring:
   application:
    name: provider8001 # 应用名称
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: provider8001   # 在eureka中显示对应的服务名字
    prefer-ip-address: true     #在eureka中下边的访问路径可以显示IP地址
 
info: # 在eureka中可以点击info链接，显示有值。链接后的内容就是在这里配置的
  app.name: provider8081
  company.name: puruan
  build.artifactId: zhangjiang
  build.version: 2021

